### ISSUE TITLE
Console error when opening double chest

### ISSUE THREAD

**Issue by JangoBritt** [bud-aj29/BE_Easy_Item_Dump#1]
Hey Bud, I wanted to share with you an error message I got when opening a double chest:

`
[UI][error]-UI Control: large_chest_screen | UI Control: variables_button_mappings_and_controls | UI Control: safezone_screen_matrix | UI Control: inner_matrix | UI Control: safezone_screen_panel | UI Control: root_screen_panel | UI Control: root_panel | UI Control: from_inventory_filtered | UI Control: stack_panel_2_2 | JSON UI parse failure: The factory name should not be empty!`

everything seems to be working fine in-game though

**Comment by bud-aj29** [comment]
The pack was made in 1.20, the error your getting came with 1.21. I'm aware and will fix it in the future. Thanks for your feedback!

**Comment by bud-aj29** [comment]
Found the error fix. Correction will be implemented in next release.
