### ISSUE TITLE
Question: Modded containers

### ISSUE THREAD

**Issue by JangoBritt** [bud-aj29/BE_Easy_Item_Dump#2]
Hey. this isn't an issue, but maybe a feature request... is there a way to implement this feature for modded containers?

We're currently using EndXenocMC's Medieval Furniture, and MrCrayFish Furniture, for modded containers, like shelves, cabinets, etc... I'm wondering how this would be implemented for container entities other than chests & barrels?

**Comment by bud-aj29** [comment]
Though I don't use any modded containers myself. I believe it would be possible for you to apply this to your container screen. Given that the vanilla control schemes (e.g. auto_place) still work in your pack.
