### ISSUE TITLE
Only 1 of 4 buttons are working

### ISSUE THREAD

**Issue by Rayth** [bud-aj29/BE_Easy_Item_Dump#3]
Only pack I have active, and the only button that works is chest to person. None of the other 3 buttons are actually doing anything.

**Comment by Rayth** [comment]
Ok update: the 2 bottom buttons I just realised are for when you're holding an item, but the one for emptying full inventory to a chest isn't working for me

**Comment by 1jx2** [comment]
It is suggested to add a button for discarding items and a button for discarding certain items in the box.
